### ISSUE TITLE
Dates on posts

### ISSUE THREAD

**Issue by jarofgreen** [edjug/edjug.github.io#2]
Hello,

I'm looking at https://github.com/edjug/edjug.github.io/blob/master/_posts/meetups/2016-30-11-november-meetup.md

Is it normal for you to date the post as the same date as the event?

In this case, the intended use is to date it to the date the blog post was created.

Just curious - thanks.

**Comment by hcoles** [comment]
For meetups I've been intentionally setting the post date to the date of the event. This is possibly a terrible idea, but the rationale is that the date is pretty prominent in most of the default templates and the site isn't really a blog a such.

**Comment by jarofgreen** [comment]
Well, it certainly is not the intended use and it means things like your ATOM feed is wrong. :-) But there you go. I've put something in to deal with it.
